#pragma once

const Real PI = 3.14159265359f;
const Real RADS_PER_DEGREE = PI / 180.0f;
const Real LOGICFRAMES_PER_SECOND = 5;
const Real MSEC_PER_SECOND = 1000;
const Real LOGICFRAMES_PER_MSEC_REAL = (LOGICFRAMES_PER_SECOND / MSEC_PER_SECOND);
const Real LOGICFRAMES_PER_SECONDS_REAL = (Real)LOGICFRAMES_PER_SECOND;
const Real SECONDS_PER_LOGICFRAME_REAL = 1.0f / LOGICFRAMES_PER_SECONDS_REAL;